### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by Br1ght0ne** [HerringtonDarkholme/ast-grep#31]
I wanted to package `ast-grep` for Homebrew and Nixpkgs, but I can't without a license.

**Comment by HerringtonDarkholme** [comment]
Thanks! c9aff6ace291c5a02e48446aa9be1d471b763ca2 added the license.

**Comment by ahmedelgabri** [comment]
@Br1ght0ne did you manage to do this? I was also looking into installing it through either Nix or Homebrew
