### ISSUE TITLE
Complex examples

### ISSUE THREAD

**Issue by Masynchin** [HerringtonDarkholme/ast-grep#6]
I have the following Rust code:

~~~rust
patterns = match config.include.clone() {
    Some(patterns) => patterns,
    None => Vec::from([cwd
        .join("**/*.toml")
        .normalize()
        .to_string_lossy()
        .into_owned()]),
};
~~~

And I want to replace with this:

~~~rust
patterns = config.include.clone().unwrap_or_else(|| {
    Vec::from([cwd
        .join("**/*.toml")
        .normalize()
        .to_string_lossy()
        .into_owned()])
})
~~~

I tried to do it with this command:

~~~shell
sg -p '$A match { Some($X) => $X, None => $N, }' -r '$A.unwrap_or_else($N)' --lang rust
~~~

But it can't match pattern. How can I solve it? Also, maybe it would be better if README has examples with this complex types of AST nodes.

**Comment by Masynchin** [comment]
@HerringtonDarkholme ping!

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for giving ast-grep a try.

I have limited bandwidth for now and it is recommended to use https://tree-sitter.github.io/tree-sitter/playground to help you debug.

**Comment by HerringtonDarkholme** [comment]
It looks like Rust tree sitter will reject `Some($A)` as error 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2883231/186756172-cac2b7b7-e57e-4f62-90d8-398c2c78052e.png">

**Comment by HerringtonDarkholme** [comment]
I understand the problem long ago but didn't have enough bandwidth to fix. I think I will make it high priority now.
